### ISSUE TITLE
Get webapp installed

### ISSUE THREAD

**Issue by azul** [leapcode/leap_web#223]
Please document issues you run into either here or update the documentation.

**Comment by azul** [comment]
I tried following our own readme and install instructions. They are quite a bit of a mess. Sorry for that.

Here's some things i ran into:
* we have a master and a develop branch. Current development is happening on develop and that is what github displays. But git clone will pick master by default. So please run ```git checkout origin/develop -b develop``` before moving on.
* the dependencies are listed with debian / ubuntu specific command. mac is different.
* we lack a nokogiri dependency. So ```bundle --binstubs``` is likely to fail because of a missing library.
* there's an issue with the rake task that is supposed to setup the databases. It loads some models twice.
* develop is based on rails 4 and bootstrap 3 - tests should be passing but the bootstrap markup still has issues. There may be an initial issue for you in there.

I'll be travelling most of the late afternoon so i doubt i'll get to fix them. If you run into other issues please let me know here.

**Comment by azul** [comment]
@theaamanda Thanks pointing that out. I will investigate the next time i have a clean machine to install on.
But it sounds like you managed to install and run it in the end, right?

**Comment by kaeff** [comment]
Last year we had a similar problem on some machines. I think it was related
to permissions and couch's admin party being enabled or not. We checked
that everyone set up the databases using the install scripts for Travis and
left a remark in the database doc.
Am 06.07.2016 11:38 vorm. schrieb "azul" <notifications@github.com>:

@theaamanda <https://github.com/theaamanda> Thanks pointing that out. I
will investigate the next time i have a clean machine to install on.
But it sounds like you managed to install and run it in the end, right?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/leapcode/leap_web/issues/223#issuecomment-230678844>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAVCzd6yefQgPgoUkTun5DD18FNSKj4pks5qS0ZjgaJpZM4JENQG>
.

**Comment by theaamanda** [comment]
if errors turn up when executing tests and error-message is talking of applications/javascript then following command has to be executed: git submodule update --init

**Comment by starkcoffee** [comment]
@theaamanda I'm getting
```
Migrating User#design_doc... resource not found when saving even though an id was passed
rake aborted!
CouchRest::NotFound: 404 Not Found
```

How do I create the required database?

**Comment by azul** [comment]
I will properly fix this issue in the coming days. As a workaround the databases can be created like this:
```bash
HOST="http://localhost:5984"
echo "couch version :"
curl -X GET $HOST #check if you can talk to couch locally
curl -X PUT $HOST/leap_web_sessions
curl -X PUT $HOST/leap_web_users
curl -X PUT $HOST/leap_web_tokens
curl -X PUT $HOST/leap_web_tickets
```

Sorry for the mess. :sunflower:
